<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Contoh Ulasan</name>
   <tag></tag>
   <elementGuidId>4da31309-f30a-4882-8514-d2c42bcb3876</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section[8]/div/div[2]/ul/li/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9ed41c68-3af8-465c-975e-2ea2c338afd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fidyah Putri R&quot;Aplikasinya bagus, informasi terkait mobilnya lengkap dan terdapat fitur banding mobil. Cocok untuk orang sibuk yang lagi nyari mobil. Fitur-fiturnya juga lengkap, khususnya fitur home service yang sangat berguna kalau mobil rusak dan ga bisa ke bengkel. Chatbotnya juga keren dan sangat membantu.&quot;</value>
      <webElementGuid>514e5228-a062-462a-9f80-8cc95ee40f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;bg-white&quot;]/section[@class=&quot;text-reliableBlack bg-reliableBlack5 mx-4 md:mx-0 px-5 md:px-0 py-3 md:py-16&quot;]/div[@class=&quot;md:container&quot;]/div[@class=&quot;review-container&quot;]/ul[@class=&quot;px-2&quot;]/li[@class=&quot;flex justify-between gap-3 pb-[10px] mb-[10px] border-b border-reliableBlack70 last:border-none lg:border-[#E7E7E7] lg:pb-5 lg:mb-5&quot;]/div[1]</value>
      <webElementGuid>f70f7e72-9557-48e0-9afa-0eb9389e5986</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section[8]/div/div[2]/ul/li/div</value>
      <webElementGuid>a6da2d01-5187-4bcc-8434-ac3c38c824e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/div</value>
      <webElementGuid>af8d0c82-8fe7-48fc-92dc-d524ce30818d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Fidyah Putri R&quot;Aplikasinya bagus, informasi terkait mobilnya lengkap dan terdapat fitur banding mobil. Cocok untuk orang sibuk yang lagi nyari mobil. Fitur-fiturnya juga lengkap, khususnya fitur home service yang sangat berguna kalau mobil rusak dan ga bisa ke bengkel. Chatbotnya juga keren dan sangat membantu.&quot;' or . = 'Fidyah Putri R&quot;Aplikasinya bagus, informasi terkait mobilnya lengkap dan terdapat fitur banding mobil. Cocok untuk orang sibuk yang lagi nyari mobil. Fitur-fiturnya juga lengkap, khususnya fitur home service yang sangat berguna kalau mobil rusak dan ga bisa ke bengkel. Chatbotnya juga keren dan sangat membantu.&quot;')]</value>
      <webElementGuid>3961c13e-ea77-42f1-ab23-86746505b299</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
