<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_APA KATA PEMBELI</name>
   <tag></tag>
   <elementGuidId>e5e388b0-1753-4f29-b763-fa6f74dd5ef4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section[8]/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8d7a6aff-f392-4b1d-bd5f-4053a86ef099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-[16px] leading-6 text-black90 break-words overflow-hidden font-bold mb-[6px] lg:text-2xl</value>
      <webElementGuid>34bde7c5-8427-4256-a97f-f88aa59ada51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>APA KATA PEMBELI?</value>
      <webElementGuid>00e859b9-f92c-4259-9efd-62c805df1b85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;bg-white&quot;]/section[@class=&quot;text-reliableBlack bg-reliableBlack5 mx-4 md:mx-0 px-5 md:px-0 py-3 md:py-16&quot;]/div[@class=&quot;md:container&quot;]/div[@class=&quot;flex justify-between mb-5&quot;]/div[1]/div[@class=&quot;text-[16px] leading-6 text-black90 break-words overflow-hidden font-bold mb-[6px] lg:text-2xl&quot;]</value>
      <webElementGuid>a465365a-036d-4a52-875d-1cfc239a5e80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section[8]/div/div/div/div</value>
      <webElementGuid>3f2f0879-f499-4180-b6c2-95ee56924374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[8]/div/div/div/div</value>
      <webElementGuid>849fceb4-5eb5-4f15-ad25-8ea8d0c18b30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'APA KATA PEMBELI?' or . = 'APA KATA PEMBELI?')]</value>
      <webElementGuid>32f07fc2-53d9-4886-8874-c4cefe34392b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
