<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_lihat lebih banyak</name>
   <tag></tag>
   <elementGuidId>4b4e71bc-e33b-4b7d-9404-332af94a4d0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='branch-expand']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#branch-expand</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>ad48f11f-733f-4e97-8370-1d5a84c2f1a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>branch-expand</value>
      <webElementGuid>a76f3999-8863-4699-82be-16a475712217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm font-semibold uppercase lg:text-base</value>
      <webElementGuid>85095c28-ba8d-4565-ae77-c253a9086be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>lihat lebih banyak</value>
      <webElementGuid>373f41a4-698b-4ba5-9bb7-9f3b03cbe7e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;branch-expand&quot;)</value>
      <webElementGuid>3f26eca1-a4f6-4316-ad64-8182f6452ed9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='branch-expand']</value>
      <webElementGuid>caae0075-9955-4cf4-9c3c-422debb84f40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section[8]/div/div[3]/div/p</value>
      <webElementGuid>cdba92c3-22f1-461d-8411-1f58b0fb8cad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/p</value>
      <webElementGuid>b7e38133-6d14-4fb9-9d6f-27520f3864bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'branch-expand' and (text() = 'lihat lebih banyak' or . = 'lihat lebih banyak')]</value>
      <webElementGuid>dea54ced-b1b2-4e27-8c5a-67c1c842480a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
