<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_MINTA PENAWARAN</name>
   <tag></tag>
   <elementGuidId>8e6e86ec-1976-45e8-afcc-1e6a67f9c979</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ask-trade-plp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ask-trade-plp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>91137fe7-b965-4836-81ad-cf4e455d9820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ask-trade-plp</value>
      <webElementGuid>22ff9c61-bb27-4e08-9f6d-62758b2eaba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lg:ml-5 px-6 h-[52px] bg-supportiveRed text-white rounded font-bold</value>
      <webElementGuid>c6563f63-9553-46f8-a2fa-bc0679ba3841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>request a quote</value>
      <webElementGuid>519e1cf8-dce8-4d13-8e9f-d13494260166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MINTA PENAWARAN</value>
      <webElementGuid>2bc17a23-d094-4fc6-9051-21d4ddc811f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;bg-white&quot;]/div[@class=&quot;z-50 md:pt-5 md:pb-4 md:border-b md:bg-white&quot;]/section[@class=&quot;bg-reliableBlack3 md:bg-white&quot;]/div[@class=&quot;flex flex-col items-center relative justify-between md:flex-row container xl:px-0&quot;]/div[@class=&quot;hidden md:flex&quot;]/button[@id=&quot;ask-trade-plp&quot;]</value>
      <webElementGuid>0bd46408-b050-46c9-bedd-8a7dcd4d8f3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ask-trade-plp']</value>
      <webElementGuid>2e2b9d1b-8b96-4598-893b-d4a497056f02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/section/div/div[2]/button[3]</value>
      <webElementGuid>8cf66975-3e1a-400c-8e63-f705b3b35e7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>4896b2a4-c88f-4680-9c78-a682a6f07cb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ask-trade-plp' and (text() = 'MINTA PENAWARAN' or . = 'MINTA PENAWARAN')]</value>
      <webElementGuid>a52c141b-fd14-49ec-877f-7303dabe03b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
