<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_FILTER</name>
   <tag></tag>
   <elementGuidId>942f17e2-00b2-4e5f-98b3-0129f7556ff3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='button-filter-plp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button-filter-plp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e7076140-3807-450c-af00-992f4a2c61d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-filter-plp</value>
      <webElementGuid>29b483ef-18f9-44bd-b930-2017bb5504b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>filter button</value>
      <webElementGuid>59adb4e3-c133-4097-b5b9-a03b2c9f2904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex bg-reliableBlack3 mr-2 h-[52px] px-3 items-center gap-2 cursor-pointer</value>
      <webElementGuid>70310a5f-b3b5-4e77-ab01-d0d105c1530d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FILTER</value>
      <webElementGuid>fe022ce5-b9a4-46cf-bb41-7ab0fb6cd726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;bg-white&quot;]/div[@class=&quot;z-50 md:pt-5 md:pb-4 md:border-b md:bg-white&quot;]/section[@class=&quot;bg-reliableBlack3 md:bg-white&quot;]/div[@class=&quot;flex flex-col items-center relative justify-between md:flex-row container xl:px-0&quot;]/div[@class=&quot;hidden md:flex&quot;]/button[@id=&quot;button-filter-plp&quot;]</value>
      <webElementGuid>0039a149-c214-4f96-90d2-5932b71504d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='button-filter-plp']</value>
      <webElementGuid>fab7a4eb-b038-4f92-8f07-51775752a187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/section/div/div[2]/button</value>
      <webElementGuid>102ef526-063e-4ca2-9ddb-9851c6ffc9ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div[2]/button</value>
      <webElementGuid>b65bdebe-77bc-4843-a8da-10779aa52845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'button-filter-plp' and (text() = 'FILTER' or . = 'FILTER')]</value>
      <webElementGuid>3b9e8d46-00fa-4043-926c-32142af8c4d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
