<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_LIST VIEW</name>
   <tag></tag>
   <elementGuidId>f2526051-e19a-40a8-847a-27eed5cf9bb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='list-view']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#list-view</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>00473159-db28-4859-9060-9bf180d279bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>list-view</value>
      <webElementGuid>c02747a0-e17f-421e-a76d-485f1e5e22db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>list-view button</value>
      <webElementGuid>18a86ef5-22e7-482e-af0d-708df5999a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex bg-reliableBlack3 h-[52px] px-3 items-center  gap-2 cursor-pointer</value>
      <webElementGuid>49949f7a-3eb5-40cb-8272-c1a9a912017b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LIST VIEW</value>
      <webElementGuid>6edef1f0-d190-46e7-ae69-faafc51bd936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;bg-white&quot;]/div[@class=&quot;z-50 md:pt-5 md:pb-4 md:border-b md:bg-white&quot;]/section[@class=&quot;bg-reliableBlack3 md:bg-white&quot;]/div[@class=&quot;flex flex-col items-center relative justify-between md:flex-row container xl:px-0&quot;]/div[@class=&quot;hidden md:flex&quot;]/button[@id=&quot;list-view&quot;]</value>
      <webElementGuid>5990b4a2-c666-4ea3-8b45-f41c78e910d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='list-view']</value>
      <webElementGuid>09176168-55c1-4182-a8dc-79f9b9bf0ed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/section/div/div[2]/button[2]</value>
      <webElementGuid>dfab167b-68c4-41bc-9dc6-11c48985006a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]</value>
      <webElementGuid>b99a4177-20a6-4d4e-80b1-462b6e776971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'list-view' and (text() = 'LIST VIEW' or . = 'LIST VIEW')]</value>
      <webElementGuid>b29f8798-495a-4ce6-bf82-f03a06fecf8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
