<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Dealer dan bengkel toyota resmi terdekat di Indonesia. Dapatkan informasi mobil, promo terbaru, layanan servis, alamat, dan jam operasional di sini</name>
   <tag></tag>
   <elementGuidId>5a764f45-32fe-4241-93dc-502f6905084e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>d34edf68-b24e-47ce-a36f-5993aee90ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-xs md:text-base</value>
      <webElementGuid>41aa9491-66a5-4eb2-8907-7949b7df5e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dealer dan bengkel toyota resmi terdekat di Indonesia. Dapatkan informasi mobil, promo terbaru, layanan servis, alamat, dan jam operasional di sini.</value>
      <webElementGuid>632355ea-d495-4944-8888-b921ba2568ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;bg-white&quot;]/div[@class=&quot;container py-5 xl:px-0&quot;]/p[@class=&quot;text-xs md:text-base&quot;]</value>
      <webElementGuid>6593a2e5-74c2-4d72-8e25-92c2d566d025</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/p</value>
      <webElementGuid>d4b41815-4fd7-470a-bf51-23dbc3585645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/p</value>
      <webElementGuid>bea7160a-0ce1-48b1-810d-fc5654c7ec9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Dealer dan bengkel toyota resmi terdekat di Indonesia. Dapatkan informasi mobil, promo terbaru, layanan servis, alamat, dan jam operasional di sini.' or . = 'Dealer dan bengkel toyota resmi terdekat di Indonesia. Dapatkan informasi mobil, promo terbaru, layanan servis, alamat, dan jam operasional di sini.')]</value>
      <webElementGuid>c4b24d9b-7210-45cf-86ad-42821d4d03ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
