<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Daftar Bengkel dan Dealer Toyota Auto2000 Terdekat (1)</name>
   <tag></tag>
   <elementGuidId>5458fbda-8eb5-4d6b-802f-aec3be7a702d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section[5]/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>5b5a3595-34f2-402c-a858-98c9f996b99a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-base font-bold text-reliableBlack uppercase mb-[10px] lg:text-2xl lg:mb-5</value>
      <webElementGuid>5d4517d0-4a3a-4ad9-adc0-cc0546969008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar Bengkel dan Dealer Toyota Auto2000 Terdekat</value>
      <webElementGuid>a89c3e0a-bdc1-4eea-b250-d48d3072d253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;bg-white&quot;]/section[@class=&quot;py-[30px] border-t-4 lg:py-20&quot;]/div[@class=&quot;container&quot;]/h2[@class=&quot;text-base font-bold text-reliableBlack uppercase mb-[10px] lg:text-2xl lg:mb-5&quot;]</value>
      <webElementGuid>649ab428-42a2-4861-9d43-f49a7ca67d96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section[5]/div/h2</value>
      <webElementGuid>356c1f4f-bc55-4434-90bd-13d52caeaa3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[5]/div/h2</value>
      <webElementGuid>ee49c390-f06b-4da6-a8cb-7ffa2421c28d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Daftar Bengkel dan Dealer Toyota Auto2000 Terdekat' or . = 'Daftar Bengkel dan Dealer Toyota Auto2000 Terdekat')]</value>
      <webElementGuid>9d636551-815f-464d-befa-958f5e5f8c67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
