<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Hubungi Kami</name>
   <tag></tag>
   <elementGuidId>4581bd86-8dac-4b68-a602-da3286446f68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav-call']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-call</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c0b15225-1989-4314-b3e0-6f0b56c8f60b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-call</value>
      <webElementGuid>4b701135-1071-4373-a3f6-ace311c27dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://auto2000.co.id/hubungi-kami?_ga=2.251439302.110673384.1707141130-713895912.1707141130</value>
      <webElementGuid>dbe970f2-e3fa-4d3f-923d-d9a05912bb81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex text-reliableBlack items-center gap-1 px-3 h-10</value>
      <webElementGuid>7aade9e0-1fcb-4b27-9c6d-de070b37cdbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hubungi Kami</value>
      <webElementGuid>b28dc84f-6029-46cf-9b51-2d837ed228dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-call&quot;)</value>
      <webElementGuid>e863b056-3100-4944-ada3-b413849fe08f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav-call']</value>
      <webElementGuid>8435bf03-622c-4b7a-95a2-4625a7ee5c4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/nav/div/div/a</value>
      <webElementGuid>0a8354bf-dcb0-46c8-9529-26a6786fef6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://auto2000.co.id/hubungi-kami?_ga=2.251439302.110673384.1707141130-713895912.1707141130')]</value>
      <webElementGuid>fdefeb26-82e0-436f-a96a-be4f40f09d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>3fdec7d6-fc61-4f0a-9328-dc0c6c34bf04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'nav-call' and @href = 'https://auto2000.co.id/hubungi-kami?_ga=2.251439302.110673384.1707141130-713895912.1707141130' and (text() = 'Hubungi Kami' or . = 'Hubungi Kami')]</value>
      <webElementGuid>c1ad0c72-24ee-4b9c-91ac-3655557328f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
