<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Masuk  Daftar</name>
   <tag></tag>
   <elementGuidId>19e05541-1151-43c4-ab2b-ecf5d3afd151</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='nav-login']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-login</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dcf02f69-c3ee-43d4-b2f1-ab46ed261bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-login</value>
      <webElementGuid>fb95f0f0-930b-4df0-a800-e1a8f53bfe5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center text-reliableBlack gap-1 pl-3 h-10</value>
      <webElementGuid>4258976b-05db-442e-aeb0-0355f2abe606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk / Daftar</value>
      <webElementGuid>f80518e3-ff7f-4b4d-82b8-1e32eda8b9e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-login&quot;)</value>
      <webElementGuid>251907ee-79b1-4550-9e14-4fc575110643</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='nav-login']</value>
      <webElementGuid>4f7da79b-8f16-4999-84dd-c1f3cddd4bf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/nav/div/div/button</value>
      <webElementGuid>6f294091-1917-4298-b883-d0863a0c574b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>ad58560d-690c-4cdd-982d-2fd37a0e4bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'nav-login' and (text() = 'Masuk / Daftar' or . = 'Masuk / Daftar')]</value>
      <webElementGuid>62d9ea1c-16cd-47c9-bb05-6dcc1ac9bc6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
