<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Event Auto2000 Jakarta Pusat (1)</name>
   <tag></tag>
   <elementGuidId>a87eb040-396b-4792-9a1f-ae601eb88db1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section[4]/div/div/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>bac9cec5-2001-4d4d-803e-7e0a30199088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-base font-bold uppercase mb-2 text-reliableBlack lg:text-2xl</value>
      <webElementGuid>b80d850c-06ce-4aa6-8b14-1bebc9706808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Event Auto2000 Jakarta Pusat</value>
      <webElementGuid>fe5f57d3-f8e8-4e54-8a72-fe0addda7524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;bg-white&quot;]/section[@class=&quot;py-6 border-t-4 lg:py-10&quot;]/div[@class=&quot;px-4 container&quot;]/div[@class=&quot;flex justify-between lg:items-center gap-2&quot;]/div[@class=&quot;flex flex-col gap-2&quot;]/h2[@class=&quot;text-base font-bold uppercase mb-2 text-reliableBlack lg:text-2xl&quot;]</value>
      <webElementGuid>7aab15eb-9549-4051-9508-ac9e8c130bed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section[4]/div/div/div/h2</value>
      <webElementGuid>e28fb23d-1258-4dea-9a46-d841edaf32ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/h2</value>
      <webElementGuid>dacf5410-6e9d-4a5f-b3d6-5b54f4377c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Event Auto2000 Jakarta Pusat' or . = 'Event Auto2000 Jakarta Pusat')]</value>
      <webElementGuid>372bfbc2-5421-467a-b0c6-b84b6da5edd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
