<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Berikut adalah Berita Seputar Auto2000 Jakarta Pusat (1)</name>
   <tag></tag>
   <elementGuidId>131c4a00-385b-4a00-a5ea-3cd9d74e89b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section[4]/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>8add9579-9be9-427a-884a-06dbbbb9bd76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-xs text-reliableBlack mb-2 lg:text-base lg:mb-6</value>
      <webElementGuid>53ea7a7d-d400-47ad-b7bf-3a0990379025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Berikut adalah Berita Seputar Auto2000 Jakarta Pusat</value>
      <webElementGuid>05a42a0e-3012-4e08-97d0-83999b12b4ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;bg-white&quot;]/section[@class=&quot;py-6 border-t-4 lg:py-10&quot;]/div[@class=&quot;px-4 container&quot;]/p[@class=&quot;text-xs text-reliableBlack mb-2 lg:text-base lg:mb-6&quot;]</value>
      <webElementGuid>ee2e7820-f621-45b7-912e-afe2806460f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section[4]/div/p</value>
      <webElementGuid>4442ef81-abd5-435d-863e-a1a678d71506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[4]/div/p</value>
      <webElementGuid>c2c659ff-06f8-4f26-b43d-3cc3a53998ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Berikut adalah Berita Seputar Auto2000 Jakarta Pusat' or . = 'Berikut adalah Berita Seputar Auto2000 Jakarta Pusat')]</value>
      <webElementGuid>ae82b1e0-0c9d-4680-94a9-937e6bc3ca80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
