<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Kebijakan Privasi</name>
   <tag></tag>
   <elementGuidId>82e4af3d-63af-4a28-9922-7098984da448</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='link-kebijakan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#link-kebijakan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>65bf812c-e99f-4e3b-bbde-5cc56a16ab6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>link-kebijakan</value>
      <webElementGuid>df2611d6-e29c-45e1-84e5-64e16d205b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block text-hyperLink font-medium lg:inline-block</value>
      <webElementGuid>942aa117-ff2e-4466-9610-86efa12f876d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>29d19a92-8469-4b59-8d43-e97365fd03f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noreferrer</value>
      <webElementGuid>33e78bdd-374e-46a5-9daf-5d23bab005cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://sit.auto2000.co.id/kebijakan-privasi</value>
      <webElementGuid>ef184033-68da-488f-bb59-b29b23299966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kebijakan Privasi</value>
      <webElementGuid>aefcf246-dc6c-47d9-b071-7b3573868c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;link-kebijakan&quot;)</value>
      <webElementGuid>6093ebb1-0f18-48dd-8f62-ad0012a4f648</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='link-kebijakan']</value>
      <webElementGuid>9e0c589f-7bbd-4048-b5fb-f3f2879bfe90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='branch-cb-policy-plp']/p/a</value>
      <webElementGuid>57e812a9-d69d-4a4f-9823-724f7684bbb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Kebijakan Privasi')]</value>
      <webElementGuid>33294bcc-1fee-4d50-a299-0fc5a5a8866b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://sit.auto2000.co.id/kebijakan-privasi')]</value>
      <webElementGuid>596be8f0-3517-404c-8a42-645097922adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p/a</value>
      <webElementGuid>869a3e76-db10-4311-b8e2-5bbfca246c15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'link-kebijakan' and @href = 'https://sit.auto2000.co.id/kebijakan-privasi' and (text() = 'Kebijakan Privasi' or . = 'Kebijakan Privasi')]</value>
      <webElementGuid>73e97533-4b4e-46f8-a5d0-fb2430893fe9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
