<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Syarat dan Ketentuan</name>
   <tag></tag>
   <elementGuidId>f1d4abfa-9730-464a-91ad-02681f2fd4ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='link-syarat']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#link-syarat</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0829ffa8-d2f7-4680-9aba-9b1992790f45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>link-syarat</value>
      <webElementGuid>725f7311-359a-4c22-8567-aadd4d3f72f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-hyperLink font-medium</value>
      <webElementGuid>4488628c-f43e-40a2-b2e7-ca12f36c3316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>5d800f8e-cf10-4ca5-938b-fa2a83fbeb75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noreferrer</value>
      <webElementGuid>96e1b234-f431-44fb-a828-38b5b8f7b300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://sit.auto2000.co.id/syarat-ketentuan-umum</value>
      <webElementGuid>70aef555-2dcc-4cca-9c59-52501915d194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Syarat dan Ketentuan</value>
      <webElementGuid>90186c29-1a7e-4e38-8139-aa8f2bd82a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;link-syarat&quot;)</value>
      <webElementGuid>5cb3c2f2-cfe8-4351-a97f-229a1f7ee6f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='link-syarat']</value>
      <webElementGuid>3d0b7788-5f23-47f2-9324-acf06d38dcbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='branch-cb-term']/label/div[2]/p/a</value>
      <webElementGuid>496ea16e-8d13-47f0-a686-ca1c078300ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Syarat dan Ketentuan')]</value>
      <webElementGuid>104b2179-1fd3-4027-95de-5bc504a77232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://sit.auto2000.co.id/syarat-ketentuan-umum')]</value>
      <webElementGuid>36b93af0-eb1b-4ee4-9b8e-cdbacbd4ec22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>6dbe9f85-29b6-4578-a87c-030c35057593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'link-syarat' and @href = 'https://sit.auto2000.co.id/syarat-ketentuan-umum' and (text() = 'Syarat dan Ketentuan' or . = 'Syarat dan Ketentuan')]</value>
      <webElementGuid>cc841eca-081e-4a58-9f1b-1783663019af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
