<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Kirim</name>
   <tag></tag>
   <elementGuidId>3b65cf0c-6a17-4482-a8e7-afa7e0de80fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='branch-submit-form-section']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#branch-submit-form-section</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3bf0dbdf-1b00-48e4-81e9-7af2d8790812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex justify-end items-center p-3 gap-x-3 text-base font-bold md:p-4 md:justify-center md:flex-1 md:rounded   cursor-default  w-full text-white bg-reliableBlack20 p-4 max-w-[300px] mx-auto !justify-center rounded</value>
      <webElementGuid>261ffa9c-030a-4c4e-8e56-e056c3f96d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>branch-submit-form-section</value>
      <webElementGuid>30785914-d872-4e95-91f0-fdc3a89f353d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>submit button</value>
      <webElementGuid>d0fb2ad2-10f1-446c-961f-0527fe1e0ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>variant</name>
      <type>Main</type>
      <value>bg-supportiveRed</value>
      <webElementGuid>f2b41d99-0bb4-4817-b5fe-9b695455c9f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kirim</value>
      <webElementGuid>c941c0a8-f3e9-4e34-8303-91146c6a8a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;branch-submit-form-section&quot;)</value>
      <webElementGuid>8194efd2-7784-451e-8078-5a7983b44912</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='branch-submit-form-section']</value>
      <webElementGuid>b3ab0f33-f4df-4583-ae3a-107213a28410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section[6]/div[2]/form/div[2]/div[3]/button</value>
      <webElementGuid>49f21dc0-703d-4f7e-bb92-b0463c276c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>5759036c-01bc-4856-8cc0-019dde53225b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'branch-submit-form-section' and (text() = 'Kirim' or . = 'Kirim')]</value>
      <webElementGuid>fbad58cb-07bb-42f4-8af4-bf00a6c927f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
