<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Waktu Perkiraan Pembelian Mobil_branch-dd-purchase-time-section</name>
   <tag></tag>
   <elementGuidId>4863f7ba-0a01-45c4-8700-862afd77960c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='branch-dd-purchase-time-section']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#branch-dd-purchase-time-section</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b87c081-5785-4f30-a880-884adcd07fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>branch-dd-purchase-time-section</value>
      <webElementGuid>45b3b65d-c374-44c1-90f1-1cb8c65dc4fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5b71c236-47b4-4e01-ba24-735e43834c77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full outline-none px-4 py-2 bg-reliableBlack3 placeholder:text-reliableBlack60 text-reliableBlack border-b border-reliableBlack30 focus:border-reliableBlack60 lg:px-5 lg:py-4 px-5 py-3.5 bg-reliableBlack3 border-[#5F5F5F] max-h-fit lg:max-h-fit focus:border-reliableBlack cursor-pointer</value>
      <webElementGuid>d2a52bbc-ea4d-4931-94be-358efc9d990c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Waktu Perkiraan Pembelian Mobil</value>
      <webElementGuid>394ad31f-172b-48a8-b0b5-d7c8f584a012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;branch-dd-purchase-time-section&quot;)</value>
      <webElementGuid>98ef4802-6272-4246-b7b8-f459add8aa34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='branch-dd-purchase-time-section']</value>
      <webElementGuid>807adb6e-a4b1-47a2-b22e-610f29a845b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section[6]/div[2]/form/div/div[4]/div/div/input</value>
      <webElementGuid>096b2b88-4b7b-4ba9-863b-695f27cc3afa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[4]/div/div/input</value>
      <webElementGuid>c82cffa9-a823-48d4-aab1-d32cd54f51ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'branch-dd-purchase-time-section' and @type = 'text' and @placeholder = 'Waktu Perkiraan Pembelian Mobil']</value>
      <webElementGuid>47038f46-d313-45b1-bede-070840419fdc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
