<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cabang (Opsional)_branch-dd-selected-branch-section</name>
   <tag></tag>
   <elementGuidId>e204fa9c-5971-4d72-9dd1-60309423f248</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='branch-dd-selected-branch-section']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#branch-dd-selected-branch-section</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3e8f743f-245a-4e7b-ab3c-819596dfc2f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>branch-dd-selected-branch-section</value>
      <webElementGuid>b861c9ea-53f0-4c1f-9245-1fa2b60feed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9062021c-c3e0-41d3-ac21-040ebe0a0a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full outline-none px-4 py-2 bg-reliableBlack3 placeholder:text-reliableBlack60 text-reliableBlack border-b border-reliableBlack30 focus:border-reliableBlack60 lg:px-5 lg:py-4 px-5 py-3.5 bg-reliableBlack3 border-[#5F5F5F] max-h-fit lg:max-h-fit focus:border-reliableBlack cursor-pointer</value>
      <webElementGuid>697b4e6f-b087-478b-b08f-3226dfb2a683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih Cabang</value>
      <webElementGuid>e019c261-4f0e-451d-80d3-a10314d35bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;branch-dd-selected-branch-section&quot;)</value>
      <webElementGuid>31188c18-1cd6-4d4b-a1e5-6fda276c7280</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='branch-dd-selected-branch-section']</value>
      <webElementGuid>ff801cfe-5b81-4217-a433-e97b3b85910a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section[6]/div[2]/form/div/div[5]/div/div/input</value>
      <webElementGuid>fab3408b-0aa3-456b-baa6-7fc144967f8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[5]/div/div/input</value>
      <webElementGuid>9fc65898-640f-4736-8ec7-0b2ac881ec7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'branch-dd-selected-branch-section' and @type = 'text' and @placeholder = 'Pilih Cabang']</value>
      <webElementGuid>38a3f857-bfbf-4afa-b108-8c1cd7f12969</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
