<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_trendingBerkendara Dengan All New Agya Bikin Hidup Makin Bahagia1 Jan 2024 - 1 Mar 2024 (1)</name>
   <tag></tag>
   <elementGuidId>34b95c52-80e7-43ca-9dac-50d369b1549a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section[3]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e7550181-4b73-4c2f-8716-8d154317ac67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grid grid-cols-2 md:grid-cols-2 lg:grid-cols-4 md:gap-6</value>
      <webElementGuid>08e4c7fb-fc3c-4aca-b57a-e73da634c7ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>trendingBerkendara Dengan All New Agya Bikin Hidup Makin Bahagia!1 Jan 2024 - 1 Mar 2024</value>
      <webElementGuid>7f851a85-55a1-4e52-97ec-6015f05a43e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;bg-white&quot;]/section[@class=&quot;my-8 container&quot;]/div[@class=&quot;grid grid-cols-2 md:grid-cols-2 lg:grid-cols-4 md:gap-6&quot;]</value>
      <webElementGuid>f748e958-8204-4ed9-9640-dfd29a7fa07a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section[3]/div[2]</value>
      <webElementGuid>727b87f7-ad78-4d72-9d8d-394442d8d62d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div[2]</value>
      <webElementGuid>17d81422-230c-4f82-a8b2-f7061188b35d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'trendingBerkendara Dengan All New Agya Bikin Hidup Makin Bahagia!1 Jan 2024 - 1 Mar 2024' or . = 'trendingBerkendara Dengan All New Agya Bikin Hidup Makin Bahagia!1 Jan 2024 - 1 Mar 2024')]</value>
      <webElementGuid>0855bb15-aec9-46c8-9262-c9a7fb428536</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
