<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_PROMO AUTO2000 Jakarta Pusat (1)</name>
   <tag></tag>
   <elementGuidId>8ef7e72d-92ba-47b5-96dd-51010a946832</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section[3]/div/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>da126f0a-baf8-4ddf-8033-440cb9fdd3d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-base font-bold uppercase text-reliableBlack mb-2 lg:text-2xl</value>
      <webElementGuid>9f592acb-94ae-4763-933c-c42d685a56d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PROMO AUTO2000 Jakarta Pusat</value>
      <webElementGuid>6f5b0b7f-670a-4d29-b4cb-41b64d7c0dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;bg-white&quot;]/section[@class=&quot;my-8 container&quot;]/div[@class=&quot;flex justify-between lg:items-center gap-2&quot;]/div[1]/h2[@class=&quot;text-base font-bold uppercase text-reliableBlack mb-2 lg:text-2xl&quot;]</value>
      <webElementGuid>baabb9e5-de62-425e-9ccf-4b890317ece4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section[3]/div/div/h2</value>
      <webElementGuid>2fbef5a9-7791-443e-8644-4a6a0e830535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>d48e5519-e801-4857-98fd-1fe6ede06733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'PROMO AUTO2000 Jakarta Pusat' or . = 'PROMO AUTO2000 Jakarta Pusat')]</value>
      <webElementGuid>066ae4b0-f5d8-41d4-8e4e-c5b663455783</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
